apiVersion: v1
kind: ServiceAccount
metadata:
  name: weibo-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weibo-controller
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weibo-controller
subjects:
  - kind: ServiceAccount
    name: weibo-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weibo-controller
